---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse

  - src: git@github.com:andrey-mishin/vector-role.git
    scm: git
    version: "1.0.0"
    name: vector-role

  - src: git@github.com:andrey-mishin/ansible-lighthouse-role.git
    scm: git
    version: "1.0.0"
    name: lighthouse-role
